/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw3;

import java.util.Arrays;
import java.util.ArrayList;
import java.util.function.BiConsumer;
import java.util.List;

public class App {
    public static void main(String[] args) {

	List<Pair<Integer, Integer>> pairs = new ArrayList();
	for (int i = 0; i < 100; i++) {
	    pairs.add(new Pair(i, i*i));
	}

	class Printer<K, V> implements BiConsumer<K, V> {
	    public void accept(K k, V v) {
		System.out.println(String.format("Got(%s, %s)", k, v));
	    }
	}
	// Non-randomized Binary Search Tree
	BinarySearchTree<Integer, Integer> bst = BinarySearchTree.fromList(pairs);

	// Randomized Binary Search Tree
	BinarySearchTree<Integer, Integer> rbst = BinarySearchTree.randomizeFromList(pairs);

	// Red-Black Tree
	RedBlackTree<Integer, Integer> rbt = RedBlackTree.fromList(pairs);

	System.out.println(String.format("Heights:\n\tbst: %d\n\trandom bst: %d\n\trbt: %d",
					 bst.height(), rbst.height(), rbt.height()));
    }
}
